### ISSUE TITLE
a couple issues with the way the pickup stuff is handled

### ISSUE THREAD

**Issue by BadsyEdgecat** [basketini-jones/duke#170] opened 2022-10-22 17:07 UTC
1. Soul Locket and Candy Heart never trigger, regardless of if it heals you
2. pickups dropped from chests will often get picked up instantly.
3. have not yet gotten to check this, but if the above soul locket and candy heart interactions indicate anything, duke may be incapable of filling Fiend Folio's Extra Vessel trinket

**Comment by ngregrichardson** [comment] 2022-10-27 01:36
Can you provide a list of mods you're using? We have zero issues with picking up stuff instantly.

**Comment by ngregrichardson** [comment] 2022-10-27 02:55
We just looked into Soul Locket and Candy Heart, and based on what is possible with the API it's impossible to get them to work with Duke or Husk. At least for Candy Heart, Duke and Husk can never pick up red hearts, which means the game's code is triggered. That's why, instead of waiting for a heart to be added to the health bar and removing it, we add it, then remove the pickup ourselves. We're also not looking to re-create the effects of in-game items from scratch. Not too sure about the FF Extra Vessel.

**Comment by BadsyEdgecat** [comment] 2022-10-28 02:44
for the soul locket effect, honestly id recommend looking into the Custom Health API that Fiend Folio and Repentance Plus use, because it basically reimplements most health mechanics to make them more pliable with mods, and the api is just a file you add to your mod rather than an external mod people have to rely on. unfortunately documentation for chapi hasnt been really made just yet but im sure if you get in contact with FF's dev team (who have a big overlap with CHAPI devs), they can probably help you out with it. if you use chapi you might even be able to dump the custom heart-picking-up system which MAY in turn fix the instant pickup glitch im having

**Comment by ngregrichardson** [comment] 2022-10-28 02:50
Unfortunately, there are many more downsides to that than upsides. Using CHAPI would require an entire mod rewrite: there is a lot more to it than just how pickups are handled. Since it is currently undocumented, it's tough to look at it and see what would be possible and where it could help us and how difficult it would be to implement if it would. CHAPI also has its fair share of bugs, and we've decided that a few items not working would not be worth months of more work for an update that would barely be noticeable.

As for the pickup bug you're having, I will again ask for the list of mods you are using when it happens. That's the only way I can help you at this point because we have been unable to cause it on our end.

**Comment by BadsyEdgecat** [comment] 2022-10-28 02:59
31 active mods, 19 of which are cosmetic/have absolutely nothing to do with pickups, StageAPI, Mod Config Menu, MiniMAPI, External Item Descriptions, Bertran, Duke (of course), Fiend Folio, Deliverance, Reverse Wheel of Fortune Rework (pretty unlikely), Tainted Treasure Rooms, and Repentance Plus

**Comment by ngregrichardson** [comment] 2022-12-12 05:28
I'm closing this because we can still not reproduce it, even with the extra mods. I'm not sure if the issues have continued, but we've consistently seen that pickups from chests are picked up correctly, and we don't believe we're doing anything on our end to change that.

**Closed by ngregrichardson** 2022-12-12 05:28 UTC
Labels: needs info
